language: node_js
node_js:
  - 0.6
sass:
  - 3.1
coffee:
  - 1.3.3
compass:
  - 0.12
before_install:
  - "sudo gem install sass"
  - "sudo gem install compass"
  - "npm install coffee-script"
  - "npm install sqwish"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"